import Anthropic from "@anthropic-ai/sdk";
import type { TicketProposal, FileTicketResult } from "./types";
import { ISSUE_TYPES } from "./jira-config";
export { TEAMS } from "./jira-config";

export const JIRA_CONFIG = {
  baseUrl: process.env.JIRA_BASE_URL || "https://viam.atlassian.net",
  cloudId: "0e4716ff-dbb4-45e2-89a8-c5c898f5fba5",
  projectKey: "APP",
  issueTypes: {
    Bug: "10084",
    Task: "10082",
  },
  teamField: "customfield_10074",
  maxPriority: "2",
  defaultLabel: "ux-research",
} as const;

function getAuthHeader(): string {
  const email = process.env.JIRA_USER_EMAIL!;
  const token = process.env.JIRA_API_TOKEN!;
  return `Basic ${Buffer.from(`${email}:${token}`).toString("base64")}`;
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AdfNode = Record<string, any>;

function inlineText(text: string): AdfNode[] {
  const nodes: AdfNode[] = [];
  const parts = text.split(/(\*[^*]+\*)/g);
  for (const part of parts) {
    if (!part) continue;
    const italicMatch = part.match(/^\*(.+)\*$/);
    if (italicMatch) {
      nodes.push({
        type: "text",
        text: italicMatch[1],
        marks: [{ type: "em" }],
      });
    } else {
      nodes.push({ type: "text", text: part });
    }
  }
  return nodes;
}

function markdownToAdf(text: string) {
  const lines = text.split("\n");
  const content: AdfNode[] = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    if (line.trim() === "") {
      i++;
      continue;
    }

    if (line.trim() === "---" || line.trim() === "___") {
      content.push({ type: "rule" });
      i++;
      continue;
    }

    const numberedMatch = line.match(/^(\d+)\.\s+(.*)/);
    if (numberedMatch) {
      const items: AdfNode[] = [];
      while (i < lines.length) {
        const m = lines[i].match(/^(\d+)\.\s+(.*)/);
        if (!m) break;
        items.push({
          type: "listItem",
          content: [
            { type: "paragraph", content: inlineText(m[2]) },
          ],
        });
        i++;
      }
      content.push({ type: "orderedList", content: items });
      continue;
    }

    // Regular paragraph — collect consecutive non-empty, non-special lines
    const paraLines: string[] = [];
    while (
      i < lines.length &&
      lines[i].trim() !== "" &&
      lines[i].trim() !== "---" &&
      lines[i].trim() !== "___" &&
      !lines[i].match(/^\d+\.\s+/)
    ) {
      paraLines.push(lines[i]);
      i++;
    }

    if (paraLines.length > 0) {
      const paraText = paraLines.join("\n");

      if (paraText.includes("](")) {
        const linkMatch = paraText.match(
          /^([\s\S]*?)\[([^\]]+)\]\(([^)]+)\)([\s\S]*)$/
        );
        if (linkMatch) {
          const nodes: AdfNode[] = [];
          if (linkMatch[1].trim())
            nodes.push(...inlineText(linkMatch[1]));
          nodes.push({
            type: "text",
            text: linkMatch[2],
            marks: [{ type: "link", attrs: { href: linkMatch[3] } }],
          });
          if (linkMatch[4].trim())
            nodes.push(...inlineText(linkMatch[4]));
          content.push({ type: "paragraph", content: nodes });
          continue;
        }
      }

      const urlMatch = paraText.match(
        /^([\s\S]*?)(https?:\/\/\S+)([\s\S]*)$/
      );
      if (urlMatch && !paraText.includes("](")) {
        const nodes: AdfNode[] = [];
        if (urlMatch[1].trim())
          nodes.push(...inlineText(urlMatch[1]));
        nodes.push({
          type: "text",
          text: urlMatch[2],
          marks: [{ type: "link", attrs: { href: urlMatch[2] } }],
        });
        if (urlMatch[3].trim())
          nodes.push(...inlineText(urlMatch[3]));
        content.push({ type: "paragraph", content: nodes });
        continue;
      }

      content.push({
        type: "paragraph",
        content: inlineText(paraText),
      });
    }
  }

  return { type: "doc", version: 1, content };
}

export function buildDescription(
  ticket: TicketProposal,
  zoomLink: string,
  zoomPasscode: string,
  sessionDate: string,
  participantName: string
): string {
  const timestampSec = ticket.suggestedTimestampMs
    ? Math.round(ticket.suggestedTimestampMs / 1000)
    : null;
  const formattedTimestamp = timestampSec
    ? `${Math.floor(timestampSec / 60)}:${String(timestampSec % 60).padStart(2, "0")}`
    : null;

  // Strip any existing "generated by Claude" line from the description to avoid duplication
  const cleanDesc = ticket.description
    .replace(/\n?\*This description was generated.*\*\s*$/, "")
    .trim();

  let footer = `\n\n---\n\n[Zoom recording of UX testing session](${zoomLink})\n\nPasscode: ${zoomPasscode}`;
  if (formattedTimestamp) {
    footer += `\n\nStart time of issue: ${formattedTimestamp}`;
  }
  footer += `\n\n*This ticket was generated by Claude from a UX testing session on ${sessionDate} with ${participantName}.*`;

  return cleanDesc + footer;
}

export async function createIssue(
  ticket: TicketProposal,
  description: string
): Promise<{ id: string; key: string; self: string }> {
  const body = {
    fields: {
      project: { key: JIRA_CONFIG.projectKey },
      issuetype: { id: ISSUE_TYPES[ticket.type] ?? ISSUE_TYPES.Task },
      summary: ticket.title,
      description: markdownToAdf(description),
      priority: { id: ticket.priorityId },
      [JIRA_CONFIG.teamField]: ticket.teamIds.map((id) => ({ id })),
      labels: ticket.labels,
    },
  };

  const res = await fetch(`${JIRA_CONFIG.baseUrl}/rest/api/3/issue`, {
    method: "POST",
    headers: {
      Authorization: getAuthHeader(),
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Jira create issue failed (${res.status}): ${err}`);
  }

  return res.json();
}

export async function uploadAttachment(
  issueKey: string,
  screenshot: Blob
): Promise<void> {
  const formData = new FormData();
  formData.append(
    "file",
    new Blob([screenshot], { type: "image/png" }),
    `${issueKey}-screenshot.png`
  );

  const res = await fetch(
    `${JIRA_CONFIG.baseUrl}/rest/api/3/issue/${issueKey}/attachments`,
    {
      method: "POST",
      headers: {
        Authorization: getAuthHeader(),
        "X-Atlassian-Token": "no-check",
      },
      body: formData,
    }
  );

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Jira upload attachment failed (${res.status}): ${err}`);
  }
}

// --- Jira helpers for additional instructions ---

async function jiraGet(path: string) {
  const res = await fetch(`${JIRA_CONFIG.baseUrl}${path}`, {
    headers: { Authorization: getAuthHeader(), "Content-Type": "application/json" },
  });
  if (!res.ok) throw new Error(`Jira GET ${path} failed (${res.status}): ${await res.text()}`);
  return res.json();
}

async function jiraPut(path: string, body: unknown) {
  const res = await fetch(`${JIRA_CONFIG.baseUrl}${path}`, {
    method: "PUT",
    headers: { Authorization: getAuthHeader(), "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`Jira PUT ${path} failed (${res.status}): ${await res.text()}`);
}

async function jiraPost(path: string, body: unknown) {
  const res = await fetch(`${JIRA_CONFIG.baseUrl}${path}`, {
    method: "POST",
    headers: { Authorization: getAuthHeader(), "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`Jira POST ${path} failed (${res.status}): ${await res.text()}`);
  const text = await res.text();
  return text ? JSON.parse(text) : null;
}

async function searchUser(query: string): Promise<string | null> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const results = (await jiraGet(`/rest/api/3/user/search?query=${encodeURIComponent(query)}`)) as any[];
  return results.length > 0 ? results[0].accountId : null;
}

async function assignIssue(issueKey: string, accountId: string) {
  await jiraPut(`/rest/api/3/issue/${issueKey}/assignee`, { accountId });
}

async function getTransitions(issueKey: string) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const data = (await jiraGet(`/rest/api/3/issue/${issueKey}/transitions`)) as { transitions: any[] };
  return data.transitions;
}

async function transitionIssue(issueKey: string, transitionId: string) {
  await jiraPost(`/rest/api/3/issue/${issueKey}/transitions`, {
    transition: { id: transitionId },
  });
}

async function addComment(issueKey: string, bodyText: string) {
  await jiraPost(`/rest/api/3/issue/${issueKey}/comment`, {
    body: markdownToAdf(bodyText),
  });
}

async function addLabels(issueKey: string, labels: string[]) {
  await jiraPut(`/rest/api/3/issue/${issueKey}`, {
    update: { labels: labels.map((l) => ({ add: l })) },
  });
}

async function setParent(issueKey: string, parentKey: string) {
  await jiraPut(`/rest/api/3/issue/${issueKey}`, {
    fields: { parent: { key: parentKey } },
  });
}

async function linkIssue(issueKey: string, linkedKey: string, linkType: string) {
  await jiraPost(`/rest/api/3/issueLink`, {
    type: { name: linkType },
    inwardIssue: { key: issueKey },
    outwardIssue: { key: linkedKey },
  });
}

interface JiraAction {
  action: "assign" | "transition" | "comment" | "add_labels" | "set_parent" | "link_issue";
  user_query?: string;
  status_name?: string;
  comment_text?: string;
  labels?: string[];
  parent_key?: string;
  linked_key?: string;
  link_type?: string;
}

export async function executeAdditionalInstructions(
  issueKey: string,
  instructions: string
): Promise<void> {
  const transitions = await getTransitions(issueKey);
  const transitionList = transitions
    .map((t: { id: string; name: string }) => `- "${t.name}" (id: ${t.id})`)
    .join("\n");

  const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY! });

  const response = await anthropic.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 1024,
    messages: [
      {
        role: "user",
        content: `You are a Jira automation assistant. A user filed a Jira ticket (${issueKey}) and wants you to perform additional actions on it.

AVAILABLE ACTIONS:
1. assign — Assign the issue to a user. Provide "user_query" (name or email to search for).
2. transition — Move issue to a status. Available transitions:
${transitionList}
3. comment — Add a comment. Provide "comment_text" (plain text or markdown). To @-mention someone, use their name and I'll resolve it.
4. add_labels — Add labels. Provide "labels" array.
5. set_parent — Make this issue a child of another ticket. Provide "parent_key" (e.g. "APP-1234").
6. link_issue — Link this issue to another ticket. Provide "linked_key" (e.g. "APP-1234") and "link_type" (one of: "Blocks", "Cloners", "Duplicate", "Relates").

USER INSTRUCTIONS: "${instructions}"

Return a JSON array of actions to perform, in order. Each action is an object with "action" and relevant fields.
Example: [{"action": "assign", "user_query": "Nat Hartman"}, {"action": "transition", "status_name": "To Do"}]

Return ONLY the JSON array, no explanation.`,
      },
    ],
  });

  const textBlock = response.content.find((b) => b.type === "text");
  if (!textBlock || textBlock.type !== "text") return;

  let raw = textBlock.text.trim();
  if (raw.startsWith("```")) {
    raw = raw.replace(/^```(?:json)?\n?/, "").replace(/\n?```$/, "");
  }

  const actions = JSON.parse(raw) as JiraAction[];

  for (const act of actions) {
    switch (act.action) {
      case "assign": {
        const accountId = await searchUser(act.user_query ?? "");
        if (accountId) {
          await assignIssue(issueKey, accountId);
        } else {
          console.warn(`Could not find Jira user for "${query}"`);
        }
        break;
      }
      case "transition": {
        const match = transitions.find(
          (t: { id: string; name: string }) =>
            t.name.toLowerCase() === act.status_name?.toLowerCase()
        );
        if (match) {
          await transitionIssue(issueKey, match.id);
        } else {
          console.warn(`No matching transition for "${act.status_name}"`);
        }
        break;
      }
      case "comment": {
        if (act.comment_text) {
          let text = act.comment_text;
          const mentionMatches = text.match(/@(\w[\w\s]*\w)/g);
          if (mentionMatches) {
            for (const mention of mentionMatches) {
              const name = mention.slice(1);
              const accountId = await searchUser(name);
              if (accountId) {
                text = text.replace(mention, `[~accountId:${accountId}]`);
              }
            }
          }
          await addComment(issueKey, text);
        }
        break;
      }
      case "add_labels": {
        if (act.labels?.length) {
          await addLabels(issueKey, act.labels);
        }
        break;
      }
      case "set_parent": {
        if (act.parent_key) {
          await setParent(issueKey, act.parent_key);
        }
        break;
      }
      case "link_issue": {
        if (act.linked_key) {
          await linkIssue(issueKey, act.linked_key, act.link_type ?? "Relates");
        }
        break;
      }
    }
  }
}

export async function createDesignSubtask(
  parentKey: string,
  parentTitle: string,
  priorityId: string
): Promise<{ key: string; url: string }> {
  const designTeamId = "10371";

  const fields = {
    project: { key: JIRA_CONFIG.projectKey },
    parent: { key: parentKey },
    issuetype: { id: ISSUE_TYPES.Task },
    summary: `[Design] ${parentTitle}`,
    priority: { id: priorityId },
    [JIRA_CONFIG.teamField]: [{ id: designTeamId }],
    labels: ["ux-research"],
  };

  const res = await fetch(`${JIRA_CONFIG.baseUrl}/rest/api/3/issue`, {
    method: "POST",
    headers: {
      Authorization: getAuthHeader(),
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ fields }),
  });

  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Jira create design subtask failed (${res.status}): ${err}`);
  }

  const issue = await res.json();
  return { key: issue.key, url: `${JIRA_CONFIG.baseUrl}/browse/${issue.key}` };
}

export async function fileTickets(
  tickets: TicketProposal[],
  screenshots: Record<string, Blob>,
  zoomLink: string,
  zoomPasscode: string,
  sessionDate: string,
  participantName: string
): Promise<FileTicketResult[]> {
  const results: FileTicketResult[] = [];

  for (let i = 0; i < tickets.length; i++) {
    const ticket = tickets[i];
    if (!ticket.included) continue;

    try {
      const description = buildDescription(
        ticket,
        zoomLink,
        zoomPasscode,
        sessionDate,
        participantName
      );

      const ticketToFile = ticket.needsDesign
        ? { ...ticket, labels: [...ticket.labels, "needs_designs"] }
        : ticket;

      const issue = await createIssue(ticketToFile, description);

      const screenshot = screenshots[String(i)];
      if (screenshot) {
        try {
          await uploadAttachment(issue.key, screenshot);
        } catch (err) {
          console.error(`Failed to upload attachment for ${issue.key}:`, err);
        }
      }

      if (ticket.needsDesign) {
        try {
          await createDesignSubtask(issue.key, ticket.title, ticket.priorityId);
        } catch (err) {
          console.error(`Failed to create design subtask for ${issue.key}:`, err);
        }
      }

      results.push({
        ticketKey: issue.key,
        url: `${JIRA_CONFIG.baseUrl}/browse/${issue.key}`,
        success: true,
      });
    } catch (err) {
      console.error(`Failed to create ticket "${ticket.title}":`, err);
      results.push({
        ticketKey: "",
        url: "",
        success: false,
      });
    }
  }

  return results;
}
